---
- hosts: all
  # local system installation
  # - hosts: localhost
  # connection: local
  # gather_facts: true
  connection: hosts.ini
  become: true # enable sudo
  pre_tasks:
    - name: pre-run | update package cache (arch)
      tags: always
      pacman:
        update_cache: yes
        # update_only: yes
      changed_when: False
      # when: ansible_distribution == "Archlinux"
      when: ansible_distribution in ["Archlinux", "ArtixLinux"]

    - name: Synchronize clock via NTP
      command: timedatectl set-ntp true
      tags:
        - sync_clock
      when: ansible_distribution in ["Archlinux", "ArtixLinux"]

    - name: pre-run | update package cache (voidlinux)
      tags: always
      community.general.xbps:
        update_cache: yes
        # update_only: yes
      # install ansible-galaxy collection install community.general.xbps
      changed_when: False
      when: ansible_distribution == "void"

    - name: Update xbps package manager (voidlinux)
      tags: always
      community.general.xbps:
        name:
          - xbps
          - xz
      when: ansible_distribution == "void"

    - name: pre-run | update package cache (debian, etc)
      tags: always
      # apt: update_cache=yes
      apt:
        update_cache: yes
        update_only: yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install python 3 if needed (Arch or Artix)
      tags: always
      raw: test -e /usr/bin/python || (pacman -Sy python --noconfirm)
      changed_when: false
      when: ansible_distribution in ["Archlinux", "ArtixLinux"]

    - name: install python 3 if needed (VoidLinux)
      tags: always
      raw: test -e /usr/bin/python || (xbps -Sy python3 --yes)
      changed_when: false
      when: ansible_distribution == "Void"

    - name: install python 3 if needed (Debian, Ubuntu, etc)
      tags: always
      raw: test -e /usr/bin/python || (apt-get -y install python3 )
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: localhost
  become: true
  roles:
    - partition
    - base
