- name: Create Partitions for Arch, Artix and VoidLinux (all hosts)
  # hosts: localhost
  # hosts: all
  hosts: "*"
  # remote_user: ansibler
  become: true
  # become_user: root
  pre_tasks:
    - name: Gathering facts ...
      gather_facts: yes
      tags: always

  # Virtual Machine
  tasks:
    block:
      - import_tasks: vm.yaml
        tags: wipefs, mkpartition
        when: ansible_product_name == "VM=Standard PC (Q35 + ICH9, 2009)"

      - import_tasks: nitro.yaml
        tags: wipefs, mkpartition
        when: ansible_product_name == "Nitro AN515-52"

      - import_tasks: raspberry.yaml
        tags: wipefs, mkpartition
        when: ansible_product_name == "NA"
        # when: ansible_nodename == "Dietpi"

      - import_tasks: macmom.yaml
        tags: wipefs, mkpartition
        when: ansible_product_name == "MacBookAir4,1"

      - import_tasks: oldmac.yaml
        tags: wipefs, mkpartition
        when: ansible_product_name == "MacbookPro4,1"
