base_arch:
  - base
  - base-devel
  - linux-lts
  - linux-lts-headers
  - linux-firmware
  - cryptsetup
  - device-mapper
  - e2fsprogs
  - inetutils
  - jfsutils
  - dropbear
  - git
  - nano
  - neovim
  - logrotate
  - intel-ucode
  - man-db
  - man-pages
  - perl
  - sysfsutils
  - texinfo
  - usbutils
  - python3
  - fzf
  - sudo
  - doas
  - duf
  - reflector
  - logrotate
  - mtools
  - dosfstools
  - btrfs-progs
  - pacman-contrib
  # others
  - ansible
  - packer
