- name: Install Arch Base Packages
  community.general.chroot:
      package: # generic package for the desired distribution
          name:
              - base
              - base-devel
              - linux-lts
              - linux-lts-headers
              - linux-firmware
              # - "{{ dropbear }}" # package name as variable
              - dropbear
              - git
              - ansible
              - nano
              - neovim
              - intel-ucode
              - fzf
              - duf
              - reflector
              - mtools
              - dosfstools
              - btrfs-progs
              - pacman-contrib
          state: latest
  when: ansible_distribution == "ArchLinux"

- name: Remove some default packages
  community.general.chroot:
      package:
          name:
              - linux
              - linux-headers
              - openssh
          state: absent
  when: ansible_distribution == "ArchLinux"

# Aur - ansible-galaxy collection install kewlfft.aur
- name: Install aur with ansible-aur
  user: name=aur_builder
  lineinfile:
      path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
      state: present
      line: "aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman"
      validate: /usr/sbin/visudo -cf %s
      create: yes

##### VOID LINUX
- name: Install Base packages on VoidLinux
  community.general.chroot:
      community.general.xbps:
          name:
              - sway # wayland wm and compositor
              - swaybg # background manager for sway
              - non-existent-package
              - xorg-server-xwayland # xorg backend for wayland
              - Waybar # bar for sway
              - mako # notification daemon
          state: latest
  when: ansible_distribution == "void"
